version: '3.7'
services:
  tat-c:
    image: tatc:withcoverage
    build:
      context: .
      dockerfile: ./container/Dockerfile
    volumes:
      - type: bind
        source: E:\results2
        target: /mission
    ports:
      - "80:80"
  redis:
    image: "redislabs/rejson"
